{% set name = 'bob.bio.face' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  skip: True  # [arm64]
  entry_points:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - "{{ PYTHON }} setup.py sdist --formats=zip"
    {% endif %}
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.io.image
    - bob.math    
    - bob.measure
    - bob.db.base
    - bob.db.atnt
    - bob.bio.base
    - bob.pipelines
    - matplotlib {{ matplotlib }}
    - scikit-image {{ scikit_image }}
    - six {{ six }}
    - tensorflow {{ tensorflow }}  # [linux]
    - imageio-ffmpeg {{ imageio_ffmpeg }}
    - opencv {{opencv}}
  run:
    - python
    - setuptools
    - {{ pin_compatible('matplotlib', max_pin="x.x") }}
    - {{ pin_compatible('six') }}
    - {{ pin_compatible('scikit-image') }}
    - {{ pin_compatible('opencv') }}
    - {{ pin_compatible('pytorch', max_pin="x.x") }}
    - {{ pin_compatible('torchvision', max_pin="x.x") }}
    - {{ pin_compatible('pytorch-lightning', max_pin="x.x") }}
    - pydeprecate==0.3.1

  run_constrained:
    - {{ pin_compatible('tensorflow') }}  # [linux]


test:
  imports:
    - {{ name }}
  commands:
    - bob bio display-face-annotations --help
    # runs tests for package only, report only what is in the package
    # creates html and xml reports and place them in specific directories
    - pytest --verbose --cov {{ name }} --cov-report term-missing --cov-report html:{{ project_dir }}/sphinx/coverage --cov-report xml:{{ project_dir }}/coverage.xml --pyargs {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx # [linux]
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx # [linux]
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - nose {{ nose }}
    - pytest {{ pytest }}
    - pytest-cov {{ pytest_cov }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - bob.db.atnt
    - tensorflow  # [linux]
    - imageio-ffmpeg {{ imageio_ffmpeg }}
    - pydeprecate==0.3.1

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Tools for running face recognition experiments
  license_family: BSD
