{% set data = load_file_data(RECIPE_DIR + '/../pyproject.toml') %}
{% set name = data['project']['name'] %}

package:
  name: {{ name }}
  version: {{ data['project']['version'] }}

source:
  path: ..

build:
  noarch: python
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - "{{ PYTHON }} -m pip install {{ SRC_DIR }} -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob
    - bob.io.base
    - bob.measure
    - bob.bio.base
    - bob.pipelines
    - clapper {{ clapper }}
    - imageio-ffmpeg {{ imageio_ffmpeg }}
    - matplotlib {{ matplotlib }}
    - opencv {{ opencv }}
    - pytorch {{ pytorch }}
    - pytorch-lightning {{ pytorch_lightning }}
    - scikit-image {{ scikit_image }}
    - tensorflow {{ tensorflow }}  # [linux]
    - torchvision {{ torchvision }}
  run:
    - python
    - setuptools
    - bob
    - bob.io.base
    - bob.measure
    - bob.bio.base
    - bob.pipelines
    - {{ pin_compatible('clapper')}}
    - {{ pin_compatible('imageio-ffmpeg') }}
    - {{ pin_compatible('matplotlib')}}
    - {{ pin_compatible('opencv') }}
    - {{ pin_compatible('pytorch') }}
    - {{ pin_compatible('pytorch-lightning') }}
    - {{ pin_compatible('scikit-image') }}
    - {{ pin_compatible('torchvision') }}

  run_constrained:
    - {{ pin_compatible('tensorflow') }}  # [linux]


test:
  imports:
    - {{ name.replace('-','_') }}
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]


about:
  home: {{ data['project']['urls']['homepage'] }}
  summary: {{ data['project']['description'] }}
  license: {{ data['project']['license']['text'] }}
  license_family: BSD
