{% set name = 'bob.bio.face' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.io.image
    - bob.learn.activation
    - bob.math
    - bob.sp
    - bob.ip.base
    - bob.ip.color
    - bob.ip.gabor
    - bob.learn.linear
    - bob.learn.em
    - bob.measure
    - bob.db.base
    - bob.db.atnt
    - bob.bio.base
    - bob.ip.facedetect
    - bob.pipelines
    - matplotlib {{ matplotlib }}
    - scikit-image {{ scikit_image }}
    - six {{ six }}
    - tensorflow {{ tensorflow }}  # [linux]
  run:
    - python
    - setuptools
    - {{ pin_compatible('matplotlib') }}
    - {{ pin_compatible('six') }}
    - {{ pin_compatible('scikit-image') }}
  run_constrained:
    - bob.learn.tensorflow
    - {{ pin_compatible('tensorflow') }}  # [linux]

test:
  imports:
    - {{ name }}
  commands:
    - bob bio display-face-annotations --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - bob.db.arface
    - bob.db.atnt
    - bob.db.gbu
    - bob.db.ijbc
    - bob.db.lfw
    - bob.db.multipie
    - bob.db.replay
    - bob.db.replaymobile
    - bob.db.xm2vts
    - bob.db.fargo
    - bob.learn.tensorflow  # [linux]
    - tensorflow  # [linux]

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Tools for running face recognition experiments
  license_family: BSD
